export const REPLYING_BAR_HEIGHT = 40;
export const PREVIEW_IMAGE_HEIGHT = 100;
export const PADDING_IMAGE_HEIGHT = 10;
export const PREVIEW_IMAGES_BAR_HEIGHT =
  PREVIEW_IMAGE_HEIGHT + PADDING_IMAGE_HEIGHT * 2;

export const IMAGE_COMMENT_HEIGHT = 180;

export const ACCESSORY_TYPE = {
  RATING: 'rating'
}
