import {SOCIAL_BUTTON_TYPES} from './actionBar';
import {
  GRID_IMAGES_LAYOUT_TYPES,
  IMAGES_WRAPPER_HEIGHT,
  IMAGES_WRAPPER_WIDTH,
  IMAGE_HORIZONTAL_HIGHLIGHT_DIMENSIONS,
  IMAGE_VERTICAL_HIGHLIGHT_DIMENSIONS,
  IMAGE_VERTICAL_NORMAL_DIMENSIONS,
  IMAGE_HORIZONTAL_NORMAL_DIMENSIONS,
  IMAGE_SPACING
} from './post';

export {
  SOCIAL_BUTTON_TYPES,
  GRID_IMAGES_LAYOUT_TYPES,
  IMAGES_WRAPPER_HEIGHT,
  IMAGES_WRAPPER_WIDTH,
  IMAGE_HORIZONTAL_HIGHLIGHT_DIMENSIONS,
  IMAGE_VERTICAL_HIGHLIGHT_DIMENSIONS,
  IMAGE_VERTICAL_NORMAL_DIMENSIONS,
  IMAGE_HORIZONTAL_NORMAL_DIMENSIONS,
  IMAGE_SPACING
};

export const SOCIAL_RELATIVE_TIME_FORMAT_DATE = 'YYYY-MM-DD HH:mm:ss';

export const SOCIAL_DATA_TYPES = {
  NEWS: 'news',
  POST: 'post'
}
