import {SOCIAL_BUTTON_TYPES} from './actionBar';
import {
  GRID_IMAGES_LAYOUT_TYPES,
  IMAGES_WRAPPER_HEIGHT,
  IMAGES_WRAPPER_WIDTH,
  IMAGE_HORIZONTAL_HIGHLIGHT_DIMENSIONS,
  IMAGE_VERTICAL_HIGHLIGHT_DIMENSIONS,
  IMAGE_VERTICAL_NORMAL_DIMENSIONS,
  IMAGE_HORIZONTAL_NORMAL_DIMENSIONS,
  IMAGE_SPACING,
} from './post';
import {
  REPLYING_BAR_HEIGHT,
  PADDING_IMAGE_HEIGHT,
  PREVIEW_IMAGES_BAR_HEIGHT,
  PREVIEW_IMAGE_HEIGHT,
  IMAGE_COMMENT_HEIGHT,
  ACCESSORY_TYPE,
} from './comments';

export {
  // actionBar
  SOCIAL_BUTTON_TYPES,
  // post
  GRID_IMAGES_LAYOUT_TYPES,
  IMAGES_WRAPPER_HEIGHT,
  IMAGES_WRAPPER_WIDTH,
  IMAGE_HORIZONTAL_HIGHLIGHT_DIMENSIONS,
  IMAGE_VERTICAL_HIGHLIGHT_DIMENSIONS,
  IMAGE_VERTICAL_NORMAL_DIMENSIONS,
  IMAGE_HORIZONTAL_NORMAL_DIMENSIONS,
  IMAGE_SPACING,
  // comments
  REPLYING_BAR_HEIGHT,
  PADDING_IMAGE_HEIGHT,
  PREVIEW_IMAGES_BAR_HEIGHT,
  PREVIEW_IMAGE_HEIGHT,
  IMAGE_COMMENT_HEIGHT,
  ACCESSORY_TYPE,
};

export const SOCIAL_RELATIVE_TIME_FORMAT_DATE = 'YYYY-MM-DD HH:mm:ss';

export const SOCIAL_DATA_TYPES = {
  NEWS: 'news',
  POST: 'post',
  PRODUCT: 'product',
};

export const MAX_RATING_VALUE = 5;
