import appConfig from 'app-config';

export const GRID_IMAGES_LAYOUT_TYPES = {
  HORIZONTAL_2_ONLY: 'h2o',
  VERTICAL_2_ONLY: 'v2o',
  SINGLE: 's',
  HORIZONTAL_1_HIGHLIGHTS: 'h1',
  HORIZONTAL_2_HIGHLIGHTS: 'h2',
  VERTICAL_1_HIGHLIGHTS: 'v1',
  VERTICAL_2_HIGHLIGHTS: 'v2',
};

export const IMAGE_SPACING = 5;
export const IMAGES_WRAPPER_HEIGHT = appConfig.device.height / 2;
export const IMAGES_WRAPPER_WIDTH = appConfig.device.width;

export const IMAGE_VERTICAL_HIGHLIGHT_DIMENSIONS =
  IMAGES_WRAPPER_HEIGHT * 0.618;
export const IMAGE_VERTICAL_NORMAL_DIMENSIONS =
  IMAGES_WRAPPER_HEIGHT - IMAGE_VERTICAL_HIGHLIGHT_DIMENSIONS - IMAGE_SPACING;

export const IMAGE_HORIZONTAL_HIGHLIGHT_DIMENSIONS =
  IMAGES_WRAPPER_WIDTH * 0.618;
export const IMAGE_HORIZONTAL_NORMAL_DIMENSIONS =
  IMAGES_WRAPPER_WIDTH - IMAGE_HORIZONTAL_HIGHLIGHT_DIMENSIONS - IMAGE_SPACING;

  export const MAX_TOTAL_UPLOAD_IMAGES = 10;