# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'my_food_new' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	# Required by RNFirebase
	pod 'Firebase/Core'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
  # Pods for my_food_new

end