# platform :ios, '9.0'

target 'my_food_new' do
  # Comment the next line if you don't want to use dynamic frameworks
 
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'

  # Pods for my_food_new
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
#    'Core',
    'RCTImage' # <- Add this line
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'
  
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'RNFirebase/Crashlytics', :path => '../node_modules/react-native-firebase/ios'
  
  pod 'ReactNativeExceptionHandler', :podspec => '../node_modules/react-native-exception-handler/ReactNativeExceptionHandler.podspec'
  
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  
  pod 'react-native-screen-brightness', :path => '../node_modules/react-native-screen-brightness'

  pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'
  
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-branch', :path => '../node_modules/react-native-branch'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'react-native-fingerprint-scanner', :path => '../node_modules/react-native-fingerprint-scanner'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'my_food_newTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
      target.remove_from_project
    end
  end
end
