import {
  CART_TYPES,
  DELIVERY_STATUS_CODE,
  CART_STATUS,
  CART_PAYMENT_STATUS,
} from 'src/constants/cart';
import {CORE} from '../core';

export const ADDITION_LIGHT = {
  //     STATUS COLOR
  // @todo: for flash message - api message.

  danger: '#ef476f',
  warning: '#ffd166',
  success: '#06d6a0',
  info: '#118ab2',
  other: '#073b4c',

  // BRAND COLOR
  // @todo: for specific brand like Facebook, Youtube,…
  facebook: '#4267B2',
  youtube: '#FF0000',

  // CART TYPE COLOR
  [CART_TYPES.NORMAL]: '#B0C0F0',
  [CART_TYPES.DROP_SHIP]: '#FF9F1C',
  [CART_TYPES.BOOKING]: '#53917E',

  // DELIVERY STATUS COLOR
  [DELIVERY_STATUS_CODE.CANCEL]: '#DED9E2',
  [DELIVERY_STATUS_CODE.SYSTEM_RECEIVED_ORDER]: '#9FA4C4',
  [DELIVERY_STATUS_CODE.SHIPPER_RECEIVED_ORDER]: '#95AFBA',
  [DELIVERY_STATUS_CODE.SHIPPER_GETTING_PACKAGES]: '#0F7173',
  [DELIVERY_STATUS_CODE.FAIL_TO_GETTING_PACKAGES]: '#EF798A',
  [DELIVERY_STATUS_CODE.DELIVERING]: '#ffd166',
  [DELIVERY_STATUS_CODE.DELIVERY_SUCCESS]: '#06d6a0',
  [DELIVERY_STATUS_CODE.DELIVERY_FAIL]: '#ef476f',
  [DELIVERY_STATUS_CODE.ORDER_RETURNING]: '#92817A',
  [DELIVERY_STATUS_CODE.ORDER_RETURNED]: '#6C7D47',
  [DELIVERY_STATUS_CODE.FOR_CONTROL]: '#17A398',

  // ORDER STATUS COLOR
  [CART_STATUS.CART_STATUS_CANCEL_1]: '#ef476f',
  [CART_STATUS.CART_STATUS_CANCEL]: '#ef476f',
  [CART_STATUS.CART_STATUS_ORDERING]: '#6F7C12',
  [CART_STATUS.CART_STATUS_READY]: '#812384',
  [CART_STATUS.CART_STATUS_ACCEPTED]: '#F46036',
  [CART_STATUS.CART_STATUS_PROCESSING]: '#986d60',
  [CART_STATUS.CART_STATUS_DELIVERY]: '#EEAA21',
  [CART_STATUS.CART_STATUS_COMPLETED]: '#06d6a0',
  [CART_STATUS.CART_STATUS_CLOSED]: '#aaaaaa',

  // PAYMENT STATUS COLOR
  [CART_PAYMENT_STATUS.UNPAID]: '#EEAA21',
  [CART_PAYMENT_STATUS.PAID]: '#06d6a0',
  [CART_PAYMENT_STATUS.CANCEL]: '#ef476f',

  // MEMBERSHIP
  standard: ['#333333', '#cccccc'],
  gold: ['#d99b2d', '#FFCF40'],
  platinum: ['#a1a3a6', '#d8dadb'],
  diamond: ['#723dc6', '#d1a0f6'],

  // OTHERS
  accent1: CORE.green500,
  accent2: CORE.blue700,
  sale: '#FD0D1B',
  marigold: '#EEAA21',
  cherry: '#da3560',
};
