import {IMAGE_RATIOS} from './ratios';

const MAX_IMAGE_UPLOAD_DIMENSION = 2048;
const IMAGE_PICKER_TYPE = {
  RN_IMAGE_CROP_PICKER: 'RN_IMAGE_CROP_PICKER',
  RN_IMAGE_PICKER: 'RN_IMAGE_PICKER',
};

export {IMAGE_RATIOS, MAX_IMAGE_UPLOAD_DIMENSION, IMAGE_PICKER_TYPE};
